/**
 * Human labels and one-line descriptions for the tokens people actually touch.
 * Anything not listed falls back to a title-cased token name, which is still
 * better than SHOUTING_SNAKE_CASE.
 */
export const DESCRIBE: Record<string, { label: string; help: string }> = {
  DIM: { label: "World size", help: "Width and height in region tiles. Fixed once a blueprint is loaded." },
  POLE: { label: "Poles", help: "Which edges of the map are polar. NONE for a painted world you have already given a climate." },
  END_YEAR: { label: "History length", help: "Years of world history before you arrive. Longer means richer, and slower." },
  BEAST_END_YEAR: { label: "Beasts stop at year", help: "Megabeast attacks are disabled after this year, or when only this percentage remain." },
  REVEAL_ALL_HISTORY: { label: "Reveal all history", help: "Show every historical event in Legends, including ones no one witnessed." },
  CULL_HISTORICAL_FIGURES: { label: "Cull unimportant figures", help: "Drop insignificant historical figures to keep saves smaller." },
  ELEVATION: { label: "Elevation", help: "Min, max, and the two random-variance values for the elevation field." },
  RAINFALL: { label: "Rainfall", help: "Min, max, and variance for rainfall." },
  TEMPERATURE: { label: "Temperature", help: "Min, max, and variance for temperature." },
  DRAINAGE: { label: "Drainage", help: "Min, max, and variance for drainage." },
  VOLCANISM: { label: "Volcanism", help: "Min, max, and variance for volcanism." },
  SAVAGERY: { label: "Savagery", help: "Min, max, and variance for savagery." },
  ELEVATION_FREQUENCY: { label: "Elevation mesh", help: "Mesh size, then five weights for bands of the min–max range. Reference bands are shown below." },
  RAIN_FREQUENCY: { label: "Rainfall mesh", help: "Mesh size and five band weights." },
  DRAINAGE_FREQUENCY: { label: "Drainage mesh", help: "Mesh size and five band weights." },
  TEMPERATURE_FREQUENCY: { label: "Temperature mesh", help: "Mesh size and five band weights." },
  SAVAGERY_FREQUENCY: { label: "Savagery mesh", help: "Mesh size and five band weights." },
  VOLCANISM_FREQUENCY: { label: "Volcanism mesh", help: "Mesh size and five band weights." },
  MINERAL_SCARCITY: { label: "Mineral scarcity", help: "Higher is rarer. 100 puts minerals everywhere; 50,000 makes them very rare." },
  MEGABEAST_CAP: { label: "Megabeasts", help: "Dragons, hydras, rocs and the like, placed at the start of history." },
  SEMIMEGABEAST_CAP: { label: "Semi-megabeasts", help: "Giants, ettins, minotaurs and cyclopes." },
  TITAN_NUMBER: { label: "Titans", help: "Number of titan types generated." },
  DEMON_NUMBER: { label: "Demon types", help: "Below two, goblin civilisations will not exist." },
  NIGHT_TROLL_NUMBER: { label: "Night trolls", help: "Night creature types that abduct and convert." },
  BOGEYMAN_NUMBER: { label: "Bogeymen", help: "Types of bogeyman." },
  NIGHTMARE_NUMBER: { label: "Nightmares", help: "Types of nightmare creature." },
  VAMPIRE_NUMBER: { label: "Vampire curses", help: "Distinct vampiric curses in the world." },
  WEREBEAST_NUMBER: { label: "Werebeast curses", help: "Distinct were-curses in the world." },
  SECRET_NUMBER: { label: "Secrets", help: "Necromantic secrets. Each can produce a necromancer and their tower." },
  REGIONAL_INTERACTION_NUMBER: { label: "Regional interactions", help: "Evil-biome effects such as reanimation." },
  DISTURBANCE_INTERACTION_NUMBER: { label: "Disturbance interactions", help: "Curses triggered by disturbing tombs." },
  EVIL_CLOUD_NUMBER: { label: "Evil clouds", help: "Types of evil weather cloud." },
  EVIL_RAIN_NUMBER: { label: "Evil rains", help: "Types of evil rain." },
  TOTAL_CIV_NUMBER: { label: "Civilisations", help: "Starting civilisations. Below about five, some races stop appearing at all." },
  TOTAL_CIV_POPULATION: { label: "Population cap", help: "Total historical population across all civilisations." },
  SITE_CAP: { label: "Site cap", help: "Maximum number of sites in the world." },
  PLAYABLE_CIVILIZATION_REQUIRED: { label: "Require a playable civ", help: "Reject worlds where no dwarven civilisation survives. Needs mountains." },
  MOUNTAIN_CAVE_MIN: { label: "Mountain caves", help: "Minimum kobold caves in mountains. Zero means no kobold civilisations." },
  NON_MOUNTAIN_CAVE_MIN: { label: "Lowland caves", help: "Minimum caves outside mountains." },
  MYTHICAL_SITE_NUM: { label: "Mysterious sites", help: "Ruins and other mythical places." },
  CAVERN_LAYER_COUNT: { label: "Cavern layers", help: "How many underground cavern layers the world has." },
  CAVERN_LAYER_OPENNESS_MIN: { label: "Cavern openness (min)", help: "How open the caverns are, at their least." },
  CAVERN_LAYER_OPENNESS_MAX: { label: "Cavern openness (max)", help: "How open the caverns are, at their most." },
  CAVERN_LAYER_PASSAGE_DENSITY_MIN: { label: "Passage density (min)", help: "Density of cavern passages, at least." },
  CAVERN_LAYER_PASSAGE_DENSITY_MAX: { label: "Passage density (max)", help: "Density of cavern passages, at most." },
  CAVERN_LAYER_WATER_MIN: { label: "Cavern water (min)", help: "How much water the caverns hold, at least." },
  CAVERN_LAYER_WATER_MAX: { label: "Cavern water (max)", help: "How much water the caverns hold, at most." },
  HAVE_BOTTOM_LAYER_1: { label: "Magma sea", help: "Include the magma sea beneath the caverns." },
  HAVE_BOTTOM_LAYER_2: { label: "Underworld", help: "Include the underworld beneath the magma sea." },
  LEVELS_ABOVE_GROUND: { label: "Levels above ground", help: "Z-levels of sky above the surface." },
  LEVELS_ABOVE_LAYER_1: { label: "Levels above first cavern", help: "Depth of rock between the surface and the first cavern." },
  LEVELS_ABOVE_LAYER_2: { label: "Levels above second cavern", help: "Rock between the first and second caverns." },
  LEVELS_ABOVE_LAYER_3: { label: "Levels above third cavern", help: "Rock between the second and third caverns." },
  LEVELS_ABOVE_LAYER_4: { label: "Levels above magma sea", help: "Rock between the last cavern and the magma sea." },
  LEVELS_ABOVE_LAYER_5: { label: "Levels above underworld", help: "Depth of the magma sea." },
  LEVELS_AT_BOTTOM: { label: "Levels at bottom", help: "Z-levels of the underworld." },
  CAVE_MIN_SIZE: { label: "Cave size (min)", help: "Smallest kobold cave." },
  CAVE_MAX_SIZE: { label: "Cave size (max)", help: "Largest kobold cave." },
  REGION_COUNTS: { label: "Required regions", help: "Minimum tiles of each biome, and how many small/medium/large regions. Rejects the world if unmet." },
  ELEVATION_RANGES: { label: "Elevation ranges", help: "Minimum tiles in each elevation band. Rejects the world if unmet." },
  RAIN_RANGES: { label: "Rainfall ranges", help: "Minimum tiles in each rainfall band. Rejects the world if unmet." },
  DRAINAGE_RANGES: { label: "Drainage ranges", help: "Minimum tiles in each drainage band. Rejects the world if unmet." },
  SAVAGERY_RANGES: { label: "Savagery ranges", help: "Minimum tiles in each savagery band. Rejects the world if unmet." },
  VOLCANISM_RANGES: { label: "Volcanism ranges", help: "Minimum tiles in each volcanism band. Rejects the world if unmet." },
  PEAK_NUMBER_MIN: { label: "Minimum peaks", help: "Rejects unless this many tiles reach elevation 400." },
  VOLCANO_MIN: { label: "Minimum volcanoes", help: "Rejects unless this many tiles have volcanism 100." },
  PARTIAL_OCEAN_EDGE_MIN: { label: "Partial ocean edges", help: "Edges that must be at least partly ocean. Rejects otherwise." },
  COMPLETE_OCEAN_EDGE_MIN: { label: "Complete ocean edges", help: "Edges that must be entirely ocean. Rejects otherwise." },
  RIVER_MINS: { label: "Minimum rivers", help: "Rivers need elevation of at least 104 somewhere. Rejects otherwise." },
  SUBREGION_MAX: { label: "Maximum subregions", help: "A varied world produces many. Rejects if exceeded." },
  EROSION_CYCLE_COUNT: { label: "Erosion cycles", help: "The game's own erosion. Kept at 0 for painted worlds so it does not chew through your terrain." },
  PERIODICALLY_ERODE_EXTREMES: { label: "Erode extremes", help: "Let the game flatten extreme peaks and valleys over history." },
  OROGRAPHIC_PRECIPITATION: { label: "Orographic rain", help: "Rain shadows behind mountains. Off for painted worlds, since you painted the rainfall." },
};

export const labelOf = (token: string) =>
  DESCRIBE[token]?.label ??
  token.toLowerCase().replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
