import { Biome, LayerType, type WorldPointData } from "#types";
import { identifyBiome } from "@helpers/biomeResolver";

/**
 * Inverse of identifyBiome: pick a biome, get the layer values that produce it.
 *
 * The table below was generated by brute-forcing the whole
 * (elevation, rainfall, temperature, drainage) space against identifyBiome and
 * taking the median of every combination that yields each biome, separately for
 * coastal and inland tiles. Every entry is verified to round-trip.
 */

export type LayerValues = {
  elevation: number;
  rainfall: number;
  temperature: number;
  drainage: number;
};

type BiomeForms = { inland?: LayerValues; coast?: LayerValues };

export const BIOME_TARGETS: Partial<Record<Biome, BiomeForms>> = {
  [Biome.ArcticOcean]: {
    inland: { elevation: 50, rainfall: 50, temperature: -10, drainage: 50 },
    coast: { elevation: 50, rainfall: 50, temperature: -10, drainage: 50 },
  },
  [Biome.Badlands]: {
    inland: { elevation: 200, rainfall: 5, temperature: 50, drainage: 80 },
    coast: { elevation: 200, rainfall: 5, temperature: 50, drainage: 80 },
  },
  [Biome.ForestedHills]: {
    inland: { elevation: 200, rainfall: 55, temperature: 50, drainage: 75 },
    coast: { elevation: 200, rainfall: 55, temperature: 50, drainage: 75 },
  },
  [Biome.FreshwaterTemperateMarsh]: {
    inland: { elevation: 200, rainfall: 50, temperature: 40, drainage: 15 },
  },
  [Biome.FreshwaterTemperateSwamp]: {
    inland: { elevation: 200, rainfall: 85, temperature: 40, drainage: 15 },
  },
  [Biome.FreshwaterTropicalMarsh]: {
    inland: { elevation: 200, rainfall: 50, temperature: 95, drainage: 15 },
  },
  [Biome.FreshwaterTropicalSwamp]: {
    inland: { elevation: 200, rainfall: 85, temperature: 95, drainage: 15 },
  },
  [Biome.Glacier]: {
    inland: { elevation: 200, rainfall: 50, temperature: -10, drainage: 85 },
    coast: { elevation: 200, rainfall: 50, temperature: -10, drainage: 85 },
  },
  [Biome.Grassland]: {
    inland: { elevation: 200, rainfall: 15, temperature: 40, drainage: 20 },
    coast: { elevation: 200, rainfall: 15, temperature: 40, drainage: 20 },
  },
  [Biome.Hills]: {
    inland: { elevation: 200, rainfall: 25, temperature: 50, drainage: 75 },
    coast: { elevation: 200, rainfall: 25, temperature: 50, drainage: 75 },
  },
  [Biome.MangroveSwamp]: {
    coast: { elevation: 200, rainfall: 75, temperature: 95, drainage: 5 },
  },
  [Biome.Mountain]: {
    inland: { elevation: 350, rainfall: 50, temperature: 40, drainage: 50 },
    coast: { elevation: 350, rainfall: 50, temperature: 40, drainage: 50 },
  },
  [Biome.RockyWasteland]: {
    inland: { elevation: 200, rainfall: 5, temperature: 50, drainage: 45 },
    coast: { elevation: 200, rainfall: 5, temperature: 50, drainage: 45 },
  },
  [Biome.SaltwaterTemperateMarsh]: {
    coast: { elevation: 200, rainfall: 50, temperature: 40, drainage: 15 },
  },
  [Biome.SaltwaterTemperateSwamp]: {
    coast: { elevation: 200, rainfall: 85, temperature: 40, drainage: 15 },
  },
  [Biome.SaltwaterTropicalMarsh]: {
    coast: { elevation: 200, rainfall: 50, temperature: 95, drainage: 15 },
  },
  [Biome.SaltwaterTropicalSwamp]: {
    coast: { elevation: 200, rainfall: 90, temperature: 95, drainage: 15 },
  },
  [Biome.SandDesert]: {
    inland: { elevation: 200, rainfall: 5, temperature: 50, drainage: 15 },
    coast: { elevation: 200, rainfall: 5, temperature: 50, drainage: 15 },
  },
  [Biome.Savanna]: {
    inland: { elevation: 200, rainfall: 25, temperature: 40, drainage: 20 },
    coast: { elevation: 200, rainfall: 25, temperature: 40, drainage: 20 },
  },
  [Biome.Taiga]: {
    inland: { elevation: 215, rainfall: 85, temperature: 5, drainage: 65 },
    coast: { elevation: 215, rainfall: 85, temperature: 5, drainage: 65 },
  },
  [Biome.TemperateBroadleafForest]: {
    inland: { elevation: 200, rainfall: 90, temperature: 75, drainage: 65 },
    coast: { elevation: 200, rainfall: 90, temperature: 75, drainage: 65 },
  },
  [Biome.TemperateConiferousForest]: {
    inland: { elevation: 195, rainfall: 85, temperature: 35, drainage: 65 },
    coast: { elevation: 195, rainfall: 85, temperature: 35, drainage: 65 },
  },
  [Biome.TemperateOcean]: {
    inland: { elevation: 50, rainfall: 60, temperature: 40, drainage: 50 },
    coast: { elevation: 50, rainfall: 60, temperature: 40, drainage: 50 },
  },
  [Biome.TemperateShrubland]: {
    inland: { elevation: 200, rainfall: 50, temperature: 40, drainage: 35 },
    coast: { elevation: 200, rainfall: 50, temperature: 40, drainage: 35 },
  },
  [Biome.TropicalConiferousForest]: {
    inland: { elevation: 200, rainfall: 70, temperature: 95, drainage: 65 },
    coast: { elevation: 200, rainfall: 70, temperature: 95, drainage: 65 },
  },
  [Biome.TropicalGrassland]: {
    inland: { elevation: 200, rainfall: 15, temperature: 95, drainage: 20 },
    coast: { elevation: 200, rainfall: 15, temperature: 95, drainage: 20 },
  },
  [Biome.TropicalMoistBroadleafForest]: {
    inland: { elevation: 200, rainfall: 90, temperature: 95, drainage: 65 },
    coast: { elevation: 200, rainfall: 90, temperature: 95, drainage: 65 },
  },
  [Biome.TropicalOcean]: {
    inland: { elevation: 50, rainfall: 30, temperature: 90, drainage: 50 },
    coast: { elevation: 50, rainfall: 30, temperature: 90, drainage: 50 },
  },
  [Biome.TropicalSavanna]: {
    inland: { elevation: 200, rainfall: 25, temperature: 95, drainage: 20 },
    coast: { elevation: 200, rainfall: 25, temperature: 95, drainage: 20 },
  },
  [Biome.TropicalShrubland]: {
    inland: { elevation: 200, rainfall: 50, temperature: 95, drainage: 35 },
    coast: { elevation: 200, rainfall: 50, temperature: 95, drainage: 35 },
  },
  [Biome.Tundra]: {
    inland: { elevation: 200, rainfall: 50, temperature: -10, drainage: 35 },
    coast: { elevation: 200, rainfall: 50, temperature: -10, drainage: 35 },
  },
};

/**
 * Coast is decided by neighbouring tiles, not by the brush, so saltwater and
 * mangrove biomes are impossible inland and freshwater ones impossible on a
 * coast. Painting one swaps to its counterpart rather than silently failing.
 */
const COAST_SWAP: Partial<Record<Biome, Biome>> = {
  [Biome.SaltwaterTemperateMarsh]: Biome.FreshwaterTemperateMarsh,
  [Biome.FreshwaterTemperateMarsh]: Biome.SaltwaterTemperateMarsh,
  [Biome.SaltwaterTropicalMarsh]: Biome.FreshwaterTropicalMarsh,
  [Biome.FreshwaterTropicalMarsh]: Biome.SaltwaterTropicalMarsh,
  [Biome.SaltwaterTemperateSwamp]: Biome.FreshwaterTemperateSwamp,
  [Biome.FreshwaterTemperateSwamp]: Biome.SaltwaterTemperateSwamp,
  [Biome.SaltwaterTropicalSwamp]: Biome.FreshwaterTropicalSwamp,
  [Biome.FreshwaterTropicalSwamp]: Biome.SaltwaterTropicalSwamp,
  [Biome.MangroveSwamp]: Biome.FreshwaterTropicalSwamp,
};

/** The biome actually achievable at this tile, given whether it borders water. */
export function resolveVariant(target: Biome, coast: boolean): Biome {
  const forms = BIOME_TARGETS[target];
  if (forms && (coast ? forms.coast : forms.inland)) return target;
  const swap = COAST_SWAP[target];
  if (swap) {
    const alt = BIOME_TARGETS[swap];
    if (alt && (coast ? alt.coast : alt.inland)) return swap;
  }
  return target;
}

export const LAYER_OF: Record<keyof LayerValues, LayerType> = {
  elevation: LayerType.Elevation,
  rainfall: LayerType.Rainfall,
  temperature: LayerType.Temperature,
  drainage: LayerType.Drainage,
};

const KEYS: Array<keyof LayerValues> = [
  "elevation",
  "rainfall",
  "temperature",
  "drainage",
];

/**
 * Minimal edit: start from the representative, then hand back every value the
 * tile already has that is still compatible with the target. Painting forest
 * onto a hillside keeps the hillside.
 */
export function solveForBiome(
  target: Biome,
  current: WorldPointData,
  coast: boolean,
  locked?: Partial<Record<LayerType, boolean>>,
): LayerValues | null {
  const variant = resolveVariant(target, coast);
  const forms = BIOME_TARGETS[variant];
  const rep = forms && (coast ? forms.coast : forms.inland);
  if (!rep) return null;

  const out: LayerValues = { ...rep };

  // Locked layers win outright. The result may then miss the requested biome —
  // that is the honest outcome, and the caller can show what was actually made.
  for (const key of KEYS) {
    if (locked?.[LAYER_OF[key]]) out[key] = current[key];
  }

  for (const key of KEYS) {
    if (locked?.[LAYER_OF[key]]) continue;
    const trial: LayerValues = { ...out, [key]: current[key] };
    if (identifyBiome(trial as unknown as WorldPointData, coast) === variant) {
      out[key] = current[key];
    }
  }
  return out;
}

/**
 * Nudge values without leaving the biome, so painted regions have texture
 * instead of reading as a flat stamp. Reverts any nudge that would reclassify.
 */
export function jitterWithinBiome(
  values: LayerValues,
  coast: boolean,
  amount: number,
  rand: () => number,
): LayerValues {
  const biome = identifyBiome(values as unknown as WorldPointData, coast);
  const out: LayerValues = { ...values };
  for (const key of KEYS) {
    const span = key === "elevation" ? amount * 3 : amount;
    const delta = Math.round((rand() * 2 - 1) * span);
    if (!delta) continue;
    const trial: LayerValues = { ...out, [key]: out[key] + delta };
    if (identifyBiome(trial as unknown as WorldPointData, coast) === biome) {
      out[key] = trial[key];
    }
  }
  return out;
}


/** Biomes offered by the brush, grouped for the palette UI. */
export const BIOME_PALETTE: Array<{ group: string; biomes: Biome[] }> = [
  { group: "Water", biomes: [Biome.TemperateOcean, Biome.TropicalOcean, Biome.ArcticOcean] },
  { group: "Mountain & Ice", biomes: [Biome.Mountain, Biome.Glacier] },
  { group: "Hills", biomes: [Biome.Hills, Biome.ForestedHills] },
  { group: "Cold Lands", biomes: [Biome.Tundra, Biome.Taiga] },
  { group: "Forests", biomes: [
      Biome.TemperateConiferousForest, Biome.TemperateBroadleafForest,
      Biome.TropicalConiferousForest, Biome.TropicalMoistBroadleafForest] },
  { group: "Grass & Scrub", biomes: [
      Biome.Grassland, Biome.TropicalGrassland, Biome.Savanna, Biome.TropicalSavanna,
      Biome.TemperateShrubland, Biome.TropicalShrubland] },
  { group: "Wetlands", biomes: [
      Biome.FreshwaterTemperateSwamp, Biome.FreshwaterTropicalSwamp,
      Biome.FreshwaterTemperateMarsh, Biome.FreshwaterTropicalMarsh, Biome.MangroveSwamp] },
  { group: "Arid Lands", biomes: [Biome.SandDesert, Biome.Badlands, Biome.RockyWasteland] },
];
